subreddits = [
    "EarthPorn",
    "Wallpapers",
    "ServerPorn",
    "unixporn",
    "CoffeePorn",
    "battlestations",
    "Aww",
    "Beerwithaview",
    "OldSchoolCool",
    "TheWayWeWere",
    "SkyPorn",
    "spaceporn",
    "itookapicture",
    "pics"
]

download_path = "download"

# Maximum number of concurrent downloads per subreddit
concurrent_downloads = 5

[file_ext]
jpg = true
png = true
gif = true

